### ISSUE TITLE
Feature request: Just export crop rectangle

### ISSUE THREAD

**Issue by JWvanV** [TakuSemba/CropMe#1]
Heyhey, nice library.

Would it be possible to just export the cropped rectangle bounds, 
and set these as initial bound?

the use-case would be to let users manipulate the bounds of a picture. Save this, but then also adust this again later on.

Looking forward to your reply :)
JW

**Comment by TakuSemba** [comment]
sorry for the late response. 
that's would be a good idea, but there is no plan to do that.
I'll reopen this when i will give it a try.
