### ISSUE TITLE
Image Orientation

### ISSUE THREAD

**Issue by zohaibTheMobileDev** [TakuSemba/CropMe#15]
When i attach portrait image either from camera/gallery. into crop View it shows landscape image....
how to solve this ? tested on Samsung Galaxy s5.

**Comment by TakuSemba** [comment]
I believe this library does not control the orientation, so I guess you set a rotated image somehow. 
Can you check what happens if you set the same image into just a normal ImageView?

**Comment by TakuSemba** [comment]
I'm closing this because this happens when you set a rotated image into CropLayout.
You have to check the rotation and rotate it if needed. This is not what the library does for you.
