### ISSUE TITLE
Image Doesn't show up, using API level 26

### ISSUE THREAD

**Issue by ShahidAnjum** [TakuSemba/CropMe#6]
I have tried with Oreo configuration, but image doesn't visible when Uri or Bitmap is set to CropView.
On trying with Bitmap it throws an exception, file not found.

**Comment by TakuSemba** [comment]
Does this happen only on Oreo? or above Oreo?
Can you check if this still happens after v2.0.0?

**Comment by TakuSemba** [comment]
I'm closing this due to the inactivity.
